package basicauth

import (
	"context"
	"time"

	"github.com/go-logr/logr"
	"golang.org/x/crypto/bcrypt"
	v1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/client-go/tools/reference"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller"
	"sigs.k8s.io/controller-runtime/pkg/handler"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/manager"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"
	"sigs.k8s.io/controller-runtime/pkg/source"

	"github.com/mittwald/kubernetes-secret-generator/pkg/apis/types/v1alpha1"
	"github.com/mittwald/kubernetes-secret-generator/pkg/controller/crd"
	"github.com/mittwald/kubernetes-secret-generator/pkg/controller/secret"
)

var log = logf.Log.WithName("controller_basicauth_secret")

const Kind = "BasicAuth"

// Add creates a new BasicAuth Controller and adds it to the Manager. The Manager will set fields on the Controller
// and Start it when the Manager is Started.
func Add(mgr manager.Manager) error {
	return add(mgr, newReconciler(mgr))
}

// newReconciler returns a new reconcile.Reconciler
func newReconciler(mgr manager.Manager) reconcile.Reconciler {
	return &ReconcileBasicAuth{client: mgr.GetClient(), scheme: mgr.GetScheme()}
}

type ReconcileBasicAuth struct {
	// This Client, initialized using mgr.Client() above, is a split Client
	// that reads objects from the cache and writes to the apiserver
	client client.Client
	scheme *runtime.Scheme
}

// add adds a new Controller to mgr with r as the reconcile.Reconciler
func add(mgr manager.Manager, r reconcile.Reconciler) error {
	// Create a new controller
	c, err := controller.New("basicauth-controller", mgr, controller.Options{Reconciler: r})
	if err != nil {
		return err
	}

	// Watch for changes to primary resource BasicAuth
	err = c.Watch(&source.Kind{Type: &v1alpha1.BasicAuth{}}, &handler.EnqueueRequestForObject{})
	if err != nil {
		return err
	}

	return nil
}

// Reconcile reads that state of the cluster for a BasicAuth object and makes changes based on the state read
// and what is in the Secret.Spec
// Note:
// The Controller will requeue the Request to be processed again if the returned error is non-nil or
// Result.Requeue is true, otherwise upon completion it will remove the work from the queue.
func (r *ReconcileBasicAuth) Reconcile(request reconcile.Request) (reconcile.Result, error) {
	reqLogger := log.WithValues("Request.Namespace", request.Namespace, "Request.Name", request.Name)
	reqLogger.Info("Reconciling BasicAuth")
	ctx := context.Background()
	// Fetch the BasicAuth instance
	instance := &v1alpha1.BasicAuth{}
	err := r.client.Get(context.TODO(), request.NamespacedName, instance)
	if err != nil {
		if errors.IsNotFound(err) {
			// Request object not found, could have been deleted after reconcile request.
			// Owned objects are automatically garbage collected. For additional cleanup logic use finalizers.
			// Return and don't requeue
			return reconcile.Result{}, nil
		}
		// Error reading the object - requeue the request.
		return reconcile.Result{}, err
	}

	// attempt to fetch secret object described by this BasicAuth
	existing := &v1.Secret{}
	err = r.client.Get(ctx, request.NamespacedName, existing)
	if errors.IsNotFound(err) {

		return r.createNewSecret(ctx, instance, reqLogger)
	} else {
		// other error occurred
		if err != nil {
			return reconcile.Result{}, err
		}
	}
	// secret already exists
	return r.updateSecret(ctx, instance, existing, reqLogger)

}

// updateSecret attempts to update an existing Secret object with new values. Secret will only be updated,
// if it is owned by a BasicAuth CR.
func (r *ReconcileBasicAuth) updateSecret(ctx context.Context, instance *v1alpha1.BasicAuth, existing *v1.Secret, reqLogger logr.Logger) (reconcile.Result, error) {
	existingOwnerRefs := existing.OwnerReferences

	ownedByCR := false
	for _, ref := range existingOwnerRefs {
		if ref.Kind != Kind {
			continue
		} else {
			ownedByCR = true
			break
		}
	}
	if !ownedByCR {
		// secret is not owned by cr, do nothing
		reqLogger.Info("secret not generated by this cr, skipping")
		return reconcile.Result{}, nil
	}

	username := instance.Spec.Username

	// fallback in case username is empty
	if username == "" {
		username = "admin"
	}

	length := instance.Spec.Length
	encoding := instance.Spec.Encoding
	regenerate := instance.Spec.ForceRecreate

	existingAuth := existing.Data[secret.SecretFieldBasicAuthIngress]

	if len(existingAuth) > 0 && !regenerate {
		// auth is set anf regeneration is not forced, do nothing
		return reconcile.Result{}, nil
	}

	targetSecret := existing.DeepCopy()

	password, passwordHash, err := generateBasicAuthValues(reqLogger, length, encoding)
	if err != nil {
		return reconcile.Result{RequeueAfter: time.Second * 30}, err
	}

	targetSecret.Data[secret.SecretFieldBasicAuthIngress] = append([]byte(username+":"), passwordHash...)
	targetSecret.Data[secret.SecretFieldBasicAuthUsername] = []byte(username)
	targetSecret.Data[secret.SecretFieldBasicAuthPassword] = password

	return r.clientUpdateSecret(ctx, targetSecret, instance)
}

// createNewSecret creates a new basicauth secret from the provided values. The Secret's owner will be set
// as the BasicAuth that is being reconciled and a reference to the Secret will be stored in
// the CR's status
func (r *ReconcileBasicAuth) createNewSecret(ctx context.Context, instance *v1alpha1.BasicAuth, reqLogger logr.Logger) (reconcile.Result, error) {
	username := instance.Spec.Username

	// fallback in case username is empty
	if username == "" {
		username = "admin"
	}

	length := instance.Spec.Length
	encoding := instance.Spec.Encoding
	secretType := instance.Spec.Type

	values := make(map[string][]byte)

	password, passwordHash, innerErr := generateBasicAuthValues(reqLogger, length, encoding)
	if innerErr != nil {
		return reconcile.Result{RequeueAfter: time.Second * 30}, innerErr
	}

	values[secret.SecretFieldBasicAuthIngress] = append([]byte(username+":"), passwordHash...)
	values[secret.SecretFieldBasicAuthUsername] = []byte(username)
	values[secret.SecretFieldBasicAuthPassword] = password

	return r.clientCreateNewSecret(ctx, values, secretType, instance)
}

// getSecretRefAndSetStatus fetches the object reference for desiredSecret and writes it into the status of instance
func (r *ReconcileBasicAuth) getSecretRefAndSetStatus(ctx context.Context, desiredSecret *v1.Secret, instance *v1alpha1.BasicAuth) error {
	// get Secret reference for status
	stringRef, err := reference.GetReference(r.scheme, desiredSecret)
	if err != nil {
		return err
	}
	status := instance.GetStatus()
	status.SetSecret(stringRef)

	if err = r.client.Status().Update(ctx, instance); err != nil {
		return err
	}

	return nil
}

// generateBasicAuthValues returns a newly generated password and its hash with given length and encoding
func generateBasicAuthValues(reqLogger logr.Logger, length, encoding string) ([]byte, []byte, error) {
	secretLength, isByteLength, err := crd.ParseByteLength(secret.SecretLength(), length)
	if err != nil {
		reqLogger.Error(err, "could not parse length for new random string")
		return []byte{}, []byte{}, err
	}

	// secret not found, create new one
	var password []byte
	password, err = secret.GenerateRandomString(secretLength, encoding, isByteLength)
	if err != nil {
		reqLogger.Error(err, "could not generate random string")

		return []byte{}, []byte{}, err
	}

	var passwordHash []byte
	passwordHash, err = bcrypt.GenerateFromPassword(password, bcrypt.DefaultCost)
	if err != nil {
		reqLogger.Error(err, "could not hash random string")

		return []byte{}, []byte{}, err
	}

	return password, passwordHash, nil
}

// clientCreateNewSecret creates a new Secret resource, uses the client to save it to the cluster and gets its resource
// ref to set the status of instance
func (r *ReconcileBasicAuth) clientCreateNewSecret(ctx context.Context, values map[string][]byte, secretType string,
	instance *v1alpha1.BasicAuth) (reconcile.Result, error) {
	desiredSecret, err := crd.NewSecret(instance, values, secretType)
	if err != nil {
		// unable to set ownership of secret
		return reconcile.Result{Requeue: true}, err
	}

	err = r.client.Create(context.Background(), desiredSecret)
	if err != nil {
		// secret has been created at some point during this reconcile, retry
		return reconcile.Result{Requeue: true}, err
	}

	err = r.getSecretRefAndSetStatus(ctx, desiredSecret, instance)
	if err != nil {
		return reconcile.Result{Requeue: true}, err
	}
	return reconcile.Result{}, nil
}

// clientUpdateSecret updates a Secret resource, uses the client to save it to the cluster and gets its resource
// ref to set the status of instance
func (r *ReconcileBasicAuth) clientUpdateSecret(ctx context.Context, targetSecret *v1.Secret, instance *v1alpha1.BasicAuth) (reconcile.Result, error) {
	err := r.client.Update(ctx, targetSecret)
	if err != nil {
		return reconcile.Result{Requeue: true}, err
	}

	err = r.getSecretRefAndSetStatus(ctx, targetSecret, instance)
	if err != nil {
		return reconcile.Result{Requeue: true}, err
	}
	return reconcile.Result{}, nil
}
