package secret

import (
	"fmt"
	corev1 "k8s.io/api/core/v1"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"
)

const (
	AnnotationSecretAutoGenerate    = "secret-generator.v1.mittwald.de/autogenerate"
	AnnotationSecretAutoGeneratedAt = "secret-generator.v1.mittwald.de/autogenerate-generated-at"
	AnnotationSecretRegenerate      = "secret-generator.v1.mittwald.de/regenerate"
	AnnotationSecretSecure          = "secret-generator.v1.mittwald.de/secure"
	AnnotationSecretType            = "secret-generator.v1.mittwald.de/type"
	AnnotationSecretLength          = "secret-generator.v1.mittwald.de/length"
	AnnotationSecretLengthB         = "secret-generator.v1.mittwald.de/lengthB"
	AnnotationBasicAuthUsername     = "secret-generator.v1.mittwald.de/basic-auth-username"
	AnnotationSecretEncoding        = "secret-generator.v1.mittwald.de/encoding"
)

type SecretType string

const (
	SecretTypeString     SecretType = "string"
	SecretTypeSSHKeypair SecretType = "ssh-keypair"
	SecretTypeBasicAuth  SecretType = "basic-auth"
)

func (st SecretType) Validate() error {
	switch st {
	case SecretTypeString,
		SecretTypeSSHKeypair,
		SecretTypeBasicAuth:
		return nil
	}
	return fmt.Errorf("%s is not a valid secret type", st)
}

type SecretGenerator interface {
	generateData(*corev1.Secret) (reconcile.Result, error)
}
