{{- if and .Values.rbac.create .Values.rbac.clusterRole -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "mittwald:{{ include "kubernetes-secret-generator.serviceAccountName" . }}"
  labels:
  {{ include "kubernetes-secret-generator.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: "mittwald:{{ include "kubernetes-secret-generator.serviceAccountName" . }}"
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace | quote }}
    name: {{ include "kubernetes-secret-generator.serviceAccountName" . }}
{{- end -}}
