{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubernetes-secret-generator.serviceAccountName" . }}
  labels:
  {{ include "kubernetes-secret-generator.labels" . | nindent 4 }}
{{- end -}}
